version: '3.6'
services:
  db:
    image: postgres:10
    restart: always
    environment:
        POSTGRES_USER: gft
        POSTGRES_PASSWORD: 1234
        POSTGRES_DB: eagle_db
    ports:
      - "5432:5432"
    volumes:
      - pgvol:/var/lib/postgresql/data 
    networks:
      - ecosystem-network
    healthcheck:
        test: ["CMD", "pg_isready -U gft"]
        interval: 10s
        timeout: 5s
        retries: 5

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin"
      PGADMIN_DEFAULT_PASSWORD: "password"
      PGADMIN_SERVER_JSON_FILE: 
    ports:
      - "1234:80"
    depends_on:
      - db
    links:
      - "db:database"
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - ecosystem-network

  zeppelin:
    image: apache/zeppelin:0.8.1
    restart: always
    ports:
      - "9999:8080"
    volumes:
      - ./zeppelin/shared:/tmp/shared
      - ./zeppelin/data:/zeppelin/data
      - ./zeppelin/notebook:/zeppelin/notebook
    networks:
      - ecosystem-network

   
volumes:
  pgvol:
  pgadmin: 

networks:
  ecosystem-network:
    name : ecosystem-network