version: '2'

services:

  cassandra:
    image: cassandra:latest

  cqlsh:
    image: cassandra:latest
    entrypoint: cqlsh cassandra
  
  zeppelin:
    image: apache/zeppelin:0.8.1
    ports: 
      - 9999:8080

  nifi:
    image: apache/nifi:latest
    ports:
      - 8888:8080